"""Regenerate client Pydantic models from the engine schema module."""

from __future__ import annotations

import ast
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ENGINE_SCHEMA = REPO_ROOT / "engine" / "app" / "schemas" / "estimation.py"
CLIENT_MODELS = REPO_ROOT / "client" / "models.py"

EXPORT_NAMES = [
    "PreprocessingMode",
    "ExampleFormat",
    "StreamEstimationRequest",
    "ProjectType",
    "DetailLevel",
    "OutputFormat",
    "EstimationRequest",
    "EstimationResponse",
    "TokenUsage",
    "StructureCheck",
]

HEADER = '''"""Generated client-side mirrors of engine estimation schemas.

Do not edit this file by hand. Run `uv run scripts/export_models.py` from the
client directory after changing `engine/app/schemas/estimation.py`.
"""

'''


def _node_name(node: ast.AST) -> str | None:
    if isinstance(node, ast.ClassDef):
        return node.name
    if isinstance(node, ast.Assign) and len(node.targets) == 1:
        target = node.targets[0]
        if isinstance(target, ast.Name):
            return target.id
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        return node.target.id
    return None


def _extract_models(source: str) -> str:
    tree = ast.parse(source)
    lines = source.splitlines()
    stdlib_imports: list[str] = []
    third_party_imports: list[str] = []
    definitions: list[str] = []

    for node in tree.body:
        if isinstance(node, ast.Import | ast.ImportFrom):
            block = "\n".join(lines[node.lineno - 1 : node.end_lineno])
            if block.startswith(("import pydantic", "from pydantic")):
                third_party_imports.append(block)
            else:
                stdlib_imports.append(block)
            continue

        name = _node_name(node)
        if name in EXPORT_NAMES:
            definitions.append("\n".join(lines[node.lineno - 1 : node.end_lineno]))

    exported = {name for name in (_node_name(node) for node in tree.body) if name in EXPORT_NAMES}
    missing = sorted(set(EXPORT_NAMES) - exported)
    if missing:
        joined = ", ".join(missing)
        raise RuntimeError(f"Engine schema is missing expected export(s): {joined}")

    import_block = "\n".join(stdlib_imports).rstrip()
    if third_party_imports:
        import_block += "\n\n" + "\n".join(third_party_imports).rstrip()

    return import_block + "\n\n" + "\n\n\n".join(definitions).rstrip() + "\n"


def main() -> None:
    source = ENGINE_SCHEMA.read_text(encoding="utf-8")
    CLIENT_MODELS.write_text(HEADER + _extract_models(source), encoding="utf-8", newline="\n")
    client_path = CLIENT_MODELS.relative_to(REPO_ROOT)
    engine_path = ENGINE_SCHEMA.relative_to(REPO_ROOT)
    print(f"Regenerated {client_path} from {engine_path}")


if __name__ == "__main__":
    main()
